name: CI
on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: install dependencies
        run: npm install

      - name: test
        run: npm run test

      - name: lint
        run: npm run lint
